# Generated by Django 2.0.13 on 2019-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('specie', models.CharField(choices=[('cat', 'gato'), ('dog', 'cachorro')], max_length=10)),
                ('gender', models.CharField(choices=[('female', 'fêmea'), ('male', 'macho')], max_length=10)),
                ('age', models.CharField(choices=[('kitten', 'filhote'), ('young', 'jovem'), ('adult', 'adulto'), ('senior', 'idoso')], max_length=10)),
                ('size', models.CharField(choices=[('small', 'pequeno'), ('medium', 'médio'), ('large', 'grande')], max_length=10)),
                ('hair', models.CharField(choices=[('short', 'curto'), ('medium', 'médio'), ('long', 'longo')], max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
