# Generated by Django 2.0.13 on 2019-04-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doghouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
    ]
